# Generated by Django 2.0.3 on 2018-03-09 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=60, verbose_name='Гражданство')),
            ],
            options={
                'verbose_name_plural': 'Гражданства',
                'verbose_name': 'Гражданство',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'verbose_name': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=40, verbose_name='Отчество')),
                ('telephone', models.CharField(max_length=15, null=True, verbose_name='Телефон')),
                ('mobile_phone', models.CharField(max_length=15, null=True, verbose_name='Мобильный телефон')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.TextField(max_length=200, verbose_name='Место рождения')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес факт. проживания')),
                ('email', models.CharField(max_length=80, verbose_name='E-mail')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Citizenship', verbose_name='Граждaанство')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.City', verbose_name='Город факт. проживания')),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'verbose_name': 'Клиент',
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_disability', models.CharField(max_length=60, verbose_name='Вид инвалидности')),
            ],
            options={
                'verbose_name_plural': 'Инвалидности',
                'verbose_name': 'Инвалидность',
            },
        ),
        migrations.CreateModel(
            name='Pensioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pensioner', models.CharField(max_length=5, verbose_name='Пенсионер')),
            ],
            options={
                'verbose_name_plural': 'Пенсионер',
                'verbose_name': 'Пенсионер',
            },
        ),
        migrations.CreateModel(
            name='Reservist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=5, verbose_name='Военнообязанный')),
            ],
            options={
                'verbose_name_plural': 'Военнообязанный',
                'verbose_name': 'Военнообязанный',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Пол')),
            ],
            options={
                'verbose_name_plural': 'Пол',
                'verbose_name': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=100, verbose_name='Семейной положение')),
            ],
            options={
                'verbose_name_plural': 'Семейные положения',
                'verbose_name': 'Семейной положение',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='disability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Disability', verbose_name='Инвалидность'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pensioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Pensioner', verbose_name='Пенсионер'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reservist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Reservist', verbose_name='Военнообязанный'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Sex', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Status', verbose_name='Семейное положение'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
