# Generated by Django 2.0.3 on 2018-03-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Citizenship', verbose_name='Гражданство'),
        ),
    ]
