# Generated by Django 2.0.3 on 2018-03-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=60, verbose_name='Гражданство')),
            ],
            options={
                'verbose_name_plural': 'Гражданства',
                'verbose_name': 'Гражданство',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'verbose_name': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_disability', models.CharField(max_length=60, verbose_name='Вид инвалидности')),
            ],
            options={
                'verbose_name_plural': 'Инвалидности',
                'verbose_name': 'Инвалидность',
            },
        ),
        migrations.CreateModel(
            name='Pensioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pensioner', models.CharField(max_length=5, verbose_name='Пенсионер')),
            ],
            options={
                'verbose_name_plural': 'Пенсионер',
                'verbose_name': 'Пенсионер',
            },
        ),
        migrations.CreateModel(
            name='Reservist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=5, verbose_name='Военнообязанный')),
            ],
            options={
                'verbose_name_plural': 'Военнообязанный',
                'verbose_name': 'Военнообязанный',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Пол')),
            ],
            options={
                'verbose_name_plural': 'Пол',
                'verbose_name': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=100, verbose_name='Семейной положение')),
            ],
            options={
                'verbose_name_plural': 'Семейные положения',
                'verbose_name': 'Семейной положение',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=1, max_length=200, verbose_name='Адрес факт. проживания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_place',
            field=models.TextField(default=1, max_length=200, verbose_name='Место рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=1, max_length=80, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AddField(
            model_name='customer',
            name='citizenship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Citizenship', verbose_name='Гражданство'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankSystem.City', verbose_name='Город факт. проживания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='disability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Disability', verbose_name='Инвалидность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='pensioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Pensioner', verbose_name='Пенсионер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='reservist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Reservist', verbose_name='Военнообязанный'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Sex', verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankSystem.Status', verbose_name='Семейное положение'),
            preserve_default=False,
        ),
    ]
