# Generated by Django 2.0.3 on 2018-03-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='Касса', max_length=13, verbose_name='Номер банковского счета')),
                ('debits', models.FloatField(default=0, max_length=10, verbose_name='Дебет')),
                ('credits', models.FloatField(default=0, max_length=10, verbose_name='Кредит')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время проводки')),
                ('sum', models.FloatField(max_length=10, verbose_name='Сумма договора')),
                ('source_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_acc', to='deposits.BankAccount', verbose_name='')),
                ('target_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_acc', to='deposits.BankAccount', verbose_name='')),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='summ',
            new_name='sum',
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование счета'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='type',
            field=models.CharField(choices=[('Active', 'Активный'), ('Passive', 'Пассивный'), ('Active-Passive', 'Активно-Пассивный')], max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.ChartOfAccounts', verbose_name='Код счета из плана счетов'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deposits.Contract', verbose_name='Договор'),
        ),
    ]
