# Generated by Django 2.0.3 on 2018-04-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_auto_20180331_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Сумма')),
                ('rate', models.FloatField(default=0, verbose_name='Ставка')),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='interest_rate',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.Deposit', verbose_name='Депозит'),
        ),
    ]
