# Generated by Django 2.0.3 on 2018-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_auto_20180405_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end',
            field=models.DateField(null=True, verbose_name='Дата конца договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=4, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала договора'),
        ),
    ]
