# Generated by Django 2.0.3 on 2018-05-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0005_auto_20180428_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deposits.Contract', verbose_name='Договор'),
        ),
    ]
