# Generated by Django 2.0.3 on 2018-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0006_auto_20180506_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-end']},
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=5, verbose_name='Номер договора'),
        ),
    ]
